local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 1 #0.5
  publish_frequency: 1 #0.5
  static_map: true
  rolling_window: true
  width: 0.5
  height: 0.5
  resolution: 0.01