// Generated by gencpp from file lenna_msgs/OdomInformation.msg
// DO NOT EDIT!


#ifndef LENNA_MSGS_MESSAGE_ODOMINFORMATION_H
#define LENNA_MSGS_MESSAGE_ODOMINFORMATION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Imu.h>
#include <nav_msgs/Odometry.h>

namespace lenna_msgs
{
template <class ContainerAllocator>
struct OdomInformation_
{
  typedef OdomInformation_<ContainerAllocator> Type;

  OdomInformation_()
    : imu_data()
    , encoder_data()  {
    }
  OdomInformation_(const ContainerAllocator& _alloc)
    : imu_data(_alloc)
    , encoder_data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::Imu_<ContainerAllocator>  _imu_data_type;
  _imu_data_type imu_data;

   typedef  ::nav_msgs::Odometry_<ContainerAllocator>  _encoder_data_type;
  _encoder_data_type encoder_data;





  typedef boost::shared_ptr< ::lenna_msgs::OdomInformation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lenna_msgs::OdomInformation_<ContainerAllocator> const> ConstPtr;

}; // struct OdomInformation_

typedef ::lenna_msgs::OdomInformation_<std::allocator<void> > OdomInformation;

typedef boost::shared_ptr< ::lenna_msgs::OdomInformation > OdomInformationPtr;
typedef boost::shared_ptr< ::lenna_msgs::OdomInformation const> OdomInformationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lenna_msgs::OdomInformation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lenna_msgs::OdomInformation_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lenna_msgs::OdomInformation_<ContainerAllocator1> & lhs, const ::lenna_msgs::OdomInformation_<ContainerAllocator2> & rhs)
{
  return lhs.imu_data == rhs.imu_data &&
    lhs.encoder_data == rhs.encoder_data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lenna_msgs::OdomInformation_<ContainerAllocator1> & lhs, const ::lenna_msgs::OdomInformation_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lenna_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::lenna_msgs::OdomInformation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lenna_msgs::OdomInformation_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lenna_msgs::OdomInformation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lenna_msgs::OdomInformation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lenna_msgs::OdomInformation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lenna_msgs::OdomInformation_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lenna_msgs::OdomInformation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6b76b290a72e807e12ebecde034281d4";
  }

  static const char* value(const ::lenna_msgs::OdomInformation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6b76b290a72e807eULL;
  static const uint64_t static_value2 = 0x12ebecde034281d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::lenna_msgs::OdomInformation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lenna_msgs/OdomInformation";
  }

  static const char* value(const ::lenna_msgs::OdomInformation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lenna_msgs::OdomInformation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/Imu imu_data\n"
"nav_msgs/Odometry encoder_data\n"
"================================================================================\n"
"MSG: sensor_msgs/Imu\n"
"# This is a message to hold data from an IMU (Inertial Measurement Unit)\n"
"#\n"
"# Accelerations should be in m/s^2 (not in g's), and rotational velocity should be in rad/sec\n"
"#\n"
"# If the covariance of the measurement is known, it should be filled in (if all you know is the \n"
"# variance of each measurement, e.g. from the datasheet, just put those along the diagonal)\n"
"# A covariance matrix of all zeros will be interpreted as \"covariance unknown\", and to use the\n"
"# data a covariance will have to be assumed or gotten from some other source\n"
"#\n"
"# If you have no estimate for one of the data elements (e.g. your IMU doesn't produce an orientation \n"
"# estimate), please set element 0 of the associated covariance matrix to -1\n"
"# If you are interpreting this message, please check for a value of -1 in the first element of each \n"
"# covariance matrix, and disregard the associated estimate.\n"
"\n"
"Header header\n"
"\n"
"geometry_msgs/Quaternion orientation\n"
"float64[9] orientation_covariance # Row major about x, y, z axes\n"
"\n"
"geometry_msgs/Vector3 angular_velocity\n"
"float64[9] angular_velocity_covariance # Row major about x, y, z axes\n"
"\n"
"geometry_msgs/Vector3 linear_acceleration\n"
"float64[9] linear_acceleration_covariance # Row major x, y z \n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: nav_msgs/Odometry\n"
"# This represents an estimate of a position and velocity in free space.  \n"
"# The pose in this message should be specified in the coordinate frame given by header.frame_id.\n"
"# The twist in this message should be specified in the coordinate frame given by the child_frame_id\n"
"Header header\n"
"string child_frame_id\n"
"geometry_msgs/PoseWithCovariance pose\n"
"geometry_msgs/TwistWithCovariance twist\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseWithCovariance\n"
"# This represents a pose in free space with uncertainty.\n"
"\n"
"Pose pose\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/TwistWithCovariance\n"
"# This expresses velocity in free space with uncertainty.\n"
"\n"
"Twist twist\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
;
  }

  static const char* value(const ::lenna_msgs::OdomInformation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lenna_msgs::OdomInformation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.imu_data);
      stream.next(m.encoder_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OdomInformation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lenna_msgs::OdomInformation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lenna_msgs::OdomInformation_<ContainerAllocator>& v)
  {
    s << indent << "imu_data: ";
    s << std::endl;
    Printer< ::sensor_msgs::Imu_<ContainerAllocator> >::stream(s, indent + "  ", v.imu_data);
    s << indent << "encoder_data: ";
    s << std::endl;
    Printer< ::nav_msgs::Odometry_<ContainerAllocator> >::stream(s, indent + "  ", v.encoder_data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LENNA_MSGS_MESSAGE_ODOMINFORMATION_H
